### ISSUE TITLE
my parents didnt give me money to do shopping and eat out and hang out with friends lie they are poor or they really are which doesnt seem fair..............

### ISSUE THREAD

**Issue by 123seher** [geneontology/helpdesk#213]
# Welcome to the Gene Ontology!

## Please indicate your role:
You may indicate more than one ( [x] )

- [ ] Biocurator
- [ ] Domain expert
- [ ] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can [email our HelpDesk](mailto:help@geneontology.org) to avoid posting it publicly.

## Group contacts info:
Please provide your expertise (1-3 keywords):

## User info:
What is your [ORCID](https://orcid.org/register)?
What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
Which group(s) are you a part of (if not the same as above)?

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
