### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by wkpalan** [geneontology/helpdesk#215]
# Welcome to the Gene Ontology!

## Please indicate your role:
You may indicate more than one ( [x] )

- [ ] Biocurator
- [ ] Domain expert
- [x] Software developer

## GO Google access:
kokulapalan[at]gmail.com

## Group contacts info:
Functional Annotation tools, Plant protein annotation, containerized annotation tools  

## User info:
What is your [ORCID](https://orcid.org/register)?
https://orcid.org/0000-0001-7811-935X
What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
Iowa State University
Which group(s) are you a part of (if not the same as above)?

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
