### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by emanuel-schmid** [geneontology/helpdesk#221]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
This is so we know who you are and who to contact to get further information about groups, training status, etc.

## Please indicate your role:
You may indicate more than one ( [x] )

- [ ] Biocurator
- [ ] Domain expert
- [x] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can [email our HelpDesk](mailto:help@geneontology.org) to avoid posting it publicly.

## Group contacts info:
Please provide your expertise (1-3 keywords):
- biodegradation
- databases
- webservices

## User info:
What is your [ORCID](https://orcid.org/register)? https://orcid.org/0000-0002-6814-7215
What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? ETH Zurich, EAWAG
Which group(s) are you a part of (if not the same as above)?

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- ~~[ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml~~
- [x] Add user to GitHub and appropriate groups

**Comment by suzialeksander** [comment]
@kltm @pgaudet did we resolve if this user needs to be added to the users.yaml (or is that just for Noctua users?)

**Comment by pgaudet** [comment]
@kltm What is the purpose of the users.yaml file ?

**Comment by kltm** [comment]
@pgaudet users.yaml is where all user information resides. It is used to 1) control authentication and authorization on our systems 2) generate label/id mapping for noctua, etc. 3) contain general user metadata.

**Comment by suzialeksander** [comment]
Sounds like if we need to alter the users.yaml at a later time, we will do it then.  No action needed for now.  Ticket is done, only suggested action is for @emanuel-schmid to sign up to the mailing list if desired: https://mailman.stanford.edu/mailman/listinfo/go-consortium
