### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by gtay2** [geneontology/helpdesk#235]
# Welcome to the Gene Ontology!

## Name: 
Gregory J. Tawa
## Please *very* briefly describe your relation to the GO:
I work at NIH/NCATA with genomics data.  Need an easy way to interpret go annotations associated
with my gene modules
## Please indicate your role:
You may indicate more than one ( [x] )

- [ ] Biocurator
- [ X] Domain expert
- [ ] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can [email our HelpDesk](mailto:help@geneontology.org) to avoid posting it publicly.
gregory.tawa@nih.gov
## Group contacts info:
Please provide your expertise (1-3 keywords):
Molecular modeling, chemoinformatics, bioninformatics, mathematics, programming
## User info:
What is your [ORCID](https://orcid.org/0000-0002-5573-308X)?
What is the name of your organization (NIH-NCATS)? 
Which group(s) are you a part of (if not the same as above)?

## Mailing list membership:
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups

**Comment by suzialeksander** [comment]
Hi @gtay2, 

If you only need to use GO information, there is no need to sign up.  Please use what you need, all we ask is you cite us as outlined at http://geneontology.org/docs/go-citation-policy/.

The New User Onboarding is for new members of the GO Consortium, where we work to develop the Ontology and the official products of the GO (AmiGO, Noctua, data files, etc.).  Please let us know if you intended to apply to be more involved than a general user and which GOC member/group referred you, or if this wasn't the level of involvement you intended.  Also, all levels of GO users are certainly welcome to join our mailing lists if they think it will be of interest, so if you didn't mean to apply to be a core GO Consortium contributor please feel free to stay signed up to the mailing list.

**Comment by gtay2** [comment]
Will I be able to use Noctua to make GO CAMS with specialized gene lists that I have put together?
