### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by AntonPetrov** [geneontology/helpdesk#236]
# Welcome to the Gene Ontology!

## Name: 

Anton Petrov

## Please *very* briefly describe your relation to the GO:

I am the RNA Resources Project Leader at EMBL-EBI working on RNAcentral and Rfam. Both databases provide data to the GOC, and I would like to be involved in the work related to GO ncRNA annotation.

## Please indicate your role:
You may indicate more than one ( [x] )

- [X] Biocurator - as part of the Rfam curation team
- [X] Domain expert - maybe?
- [X] Software developer - I am developing software for RNAcentral and Rfam

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can [email our HelpDesk](mailto:help@geneontology.org) to avoid posting it publicly.

My ebi.ac.uk email handle is apetrov.

## Group contacts info:
Please provide your expertise (1-3 keywords):

non-coding RNA, RNA 3D structure

## User info:
What is your [ORCID](https://orcid.org/register)?
What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
Which group(s) are you a part of (if not the same as above)?

- https://orcid.org/0000-0001-7279-2682
- EMBL-EBI
- Sequence Families

## Mailing list membership:
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups

**Comment by AntonPetrov** [comment]
Hello! 

I would like to follow up on this request to make sure that you have all the necessary information to process it. 

In addition, I tried to fill out a sign up form for the 2020 GOC meeting but did not have permissions:
http://wiki.geneontology.org/index.php/2020_Paris_GOC_Meeting_Logistics

Is this something I will be able to do once this issue is resolved?

Thank you!

**Comment by kltm** [comment]
For external users who are not going to be using the GO wiki for other purposes, there is a signup form: https://forms.gle/9UjKFzZCvmmCLkoFA (from http://wiki.geneontology.org/index.php/2020_Paris_GOC_Meeting_Logistics#Attendees).

If you do need the wiki for other purposes, please let us know and we can work out how to pass credentials.

**Comment by srengel** [comment]
form gives this error:
You need permission
This form can only be viewed by users in the owner's organization.
Try contacting the owner of the form if you think this is a mistake. Learn More.

**Comment by kltm** [comment]
Ah! I did not know that--we'll contact the creator of the form.

**Comment by kltm** [comment]
@lpalbou Can the form be changed to global access?

**Comment by suzialeksander** [comment]
Hi @AntonPetrov, will you be curating for Rfam and RNAcentral, or just one (which one?), and/or another resource?

**Comment by suzialeksander** [comment]
@AntonPetrov Please check your email including spam folders for the invitation to join The Gene Ontology Consortium.  If you cannot find it, you can also visit https://github.com/geneontology to accept the invitation.

**Comment by AntonPetrov** [comment]
Thank you everyone for your help! I got the Google Drive, Google Calendar and GitHub invites. I will fill out the form once it becomes public or ask our group secretary to sign me up.

@suzialeksander, I am working on both RNAcentral and Rfam so will be curating both.

**Comment by lpalbou** [comment]
Regarding the form to register to the GOC in Paris, the registration fee has not been fixed yet, hence the page is not public yet. I have removed the link from the wiki page and will reactivate it once this is ready.

Thanks

**Comment by suzialeksander** [comment]
Internal note, ticket can be closed when PRs are resolved: 
https://github.com/geneontology/go-site/pull/1327
https://github.com/geneontology/go-site/pull/1326

**Comment by suzialeksander** [comment]
@AntonPetrov One last question- do you plan to curate using Noctua at all?

**Comment by AntonPetrov** [comment]
@suzialeksander No, I don't use Noctua. We curate using internal tools and submit the files to GOC. Let me know if you need any other info. Thanks!
