### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/helpdesk#237]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
This is so we know who you are and who to contact to get further information about groups, training status, etc.

## Please indicate your role: 
You may indicate more than one ( [x] )

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## Group contacts info:
Please provide your expertise (1-3 keywords): miRNA GO annotation

## User info:
What is your [ORCID](https://orcid.org/register)? 
https://orcid.org/0000-0003-1191-2681

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
UCL

Which group(s) are you a part of (if not the same as above)?
UCL

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to go-site/metadata/group-contacts.csv
- [x] Add user to GitHub and appropriate groups

cc
@RLovering 
@ShirinSaverimuttu

**Comment by suzialeksander** [comment]
@ShirinSaverimuttu can you send us the email address you'd like to access the GO Google Drive through? You can email us at help@geneontology.org if you don't want it posted publicly here.

**Comment by suzialeksander** [comment]
@ShirinSaverimuttu Please check your email including spam folders for the invitation to join The Gene Ontology Consortium.  If you cannot find it, you can also visit https://github.com/geneontology to accept the invitation.

**Comment by suzialeksander** [comment]
@ShirinSaverimuttu, one last thing- could you sign up to the GO mailing list? I'm not sure which email you'd prefer to use. Just visit https://mailman.stanford.edu/mailman/listinfo/go-consortium and look under "Subscribing to go-consortium".  Thanks and Welcome!

**Comment by BarbaraCzub** [comment]
Hi @suzialeksander I had a chat which @ShirinSaverimuttu and she confirmed that all this is now done, so I will close this ticket. Thank you for your help!
