### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [geneontology/helpdesk#253]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO: quickgo software engineer
This is so we know who you are and who to contact to get further information about groups, training status, etc.

## Please indicate your role: Software developer
You may indicate more than one ( [x] )

- [ ] Biocurator
- [ ] Domain expert
- [ x] Software developer

## GO Google access: i will send email to below address
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can [email our HelpDesk](mailto:help@geneontology.org) to avoid posting it publicly.

## Group contacts info: quickgo java backend
Please provide your expertise (1-3 keywords):

## User info: 220000-0001-8041-7321
What is your [ORCID](https://orcid.org/register)?

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?  EMBL-EBI

Which group(s) are you a part of (if not the same as above)? uniprot

Which GOC member(s) directed you to this form? Suzi

Will you be curating in NOCTUA? No, but i might be use it for testing/exploring purpose with reference to protein2go

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups

**Comment by rizwan-ishtiaq** [comment]
http://wiki.geneontology.org/index.php/Annotation#Annotation_Conference_Calls

**Comment by suzialeksander** [comment]
in group-contacts pending https://github.com/geneontology/go-site/pull/1494
