### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by mlkaldunski** [geneontology/helpdesk#254]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
This is so we know who you are and who to contact to get further information about groups, training status, etc. 
BioCurator, the Rat Genome Database at the Medical College of Wisconsin

## Please indicate your role:
You may indicate more than one ( [x] )

- [x ] Biocurator
- [ ] Domain expert
- [ ] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can [email our HelpDesk](mailto:help@geneontology.org) to avoid posting it publicly.
mlkal@mcw.edu

## Group contacts info: curation, annotation, physiology
Please provide your expertise (1-3 keywords):

## User info:
What is your [ORCID](https://orcid.org/register)? 0000-0003-3645-6803

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? Rat Genome Database, RGD

Which group(s) are you a part of (if not the same as above)?

Which GOC member(s) directed you to this form? Found it online after GO meeting 5/14/2020

Will you be curating in NOCTUA? No

## Mailing list membership:
- [x ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups

**Comment by suzialeksander** [comment]
in group-contacts pending https://github.com/geneontology/go-site/pull/1494
