### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by ccasalsc** [geneontology/helpdesk#275]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO: 
I am Swiss-Prot curator doing mainly Uniprot curation and GO annotation for human and other vertebrates.

## Please indicate your role:

- [x ] Biocurator
- [ ] Domain expert
- [ ] Software developer

## Group contacts info: 
Please provide your expertise (1-3 keywords): Regulation of transcription. Molecular biology.

## User info:
What is your [ORCID](https://orcid.org/register)?   http://orcid.org/0000-0001-8769-177X

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?  SIB

Which group(s) are you a part of (if not the same as above)? Swiss-Prot

Which GOC member(s) directed you to this form?  Suzi Aleksander

Will you be curating in Noctua? yes

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups

**Comment by vanaukenk** [comment]
Hi @ccasalsc 
Our apologies for the delays with this.
I've added you to the users.yaml file with permission to edit in Noctua.
I've also given you access to the GO's Google Drive and Calendar.
Please let us know if you need any additional help.

**Comment by suzialeksander** [comment]
I think this is resolved, if you're still having issues @ccasalsc please open a new ticket.
