### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by AliceDashow** [geneontology/helpdesk#301]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
This is so we know who you are and who to contact to get further information about groups, training status, etc.
Independent researcher, no affiliation. No GO training is needed. In the past, I worked in UniProt-GOA (Under the old name Aleksandra Shypitsyna. Have an account in Noctua with this name and GOA affiliation). So I would be very grateful whether you could create a new one or update the old account).

## Please indicate your role:
You may indicate more than one ( [x] )

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can email our HelpDesk at "help" at our domain, geneontology.org, to avoid posting it publicly.

## Group contacts info:
Please provide your expertise (1-3 keywords):
neurobiology, molecular biology

## User info:
What is your [ORCID](https://orcid.org/register)?
https://orcid.org/0000-0003-3829-1600

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
No affiliation

Which group(s) are you a part of (if not the same as above)?
No affiliation

Which GOC member(s) directed you to this form? 
---

Will you be curating in Noctua?
Yes

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
~~- [ ] Add user to go-site/metadata/group-contacts.csv~~ N/A
- [x] Add user to go-site/metadata/users.yaml ~~and any additional groups to go-site/metadata/groups.yaml~~
- [x] Add user to GitHub and appropriate groups

**Comment by suzialeksander** [comment]
Hi Alice, 

We're currently figuring out how to give you Noctua permissions, I'll let you know when that's done.  In the meantime do you need a new email to be re-added to the GO Drive/Calendar - and if so should I use the one you've been emailing us this week?

**Comment by AliceDashow** [comment]
Hi Suzi, 

Yes, please, it is better to use the outlook email address, not the old one. 
Thank you very much!

**Comment by suzialeksander** [comment]
Hi Alice, 
I've added your outlook email to the Calendar and Drive.  We're just waiting on approval for Noctua permissions, it shouldn't be too much longer

**Comment by AliceDashow** [comment]
Hi Suzi, 

Great! Thank you very much!

**Comment by suzialeksander** [comment]
Ok, I think you’re all set. Let me know if you can’t get Noctua to go you in or anything.

**Comment by AliceDashow** [comment]
Hi Suzi, 

I am afraid Noctua does not let me log in. Furthermore, I could not see my name in the list of contributors. What would you suggest how to fix it?

**Comment by vanaukenk** [comment]
Hi @AliceDashow 
I'll refresh the Noctua users list right now.  Please wait about 30 minutes and then try again and let us know if you're still having trouble.

Thanks,
--Kimberly

**Comment by zebrafishembryo** [comment]
Hi Kimberly, 

Great! It seems to be working fine now. 
Thanks a lot!!

**Comment by AliceDashow** [comment]
Hi Kimberly,

Great! It seems to be working fine now.
Thanks a lot!!

**Comment by vanaukenk** [comment]
You're welcome!!

Please let us know if you have any questions about Noctua and GO-CAMs.  Next Tuesday, the 24th, we'll have a GO-CAM office hours call  at 11am EDT.  It'd be great if you could join us then!
