### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by c02080219** [geneontology/helpdesk#332]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
I am YuanChing Chen, a researcher from National Tsing Hua University. I am currently doing research related to Parkinson's disease and melanoma, and I hope to use Noctua (GO-CAMs) to present the results of the research.
## Please indicate your role:
You may indicate more than one ( [x] )

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## GO Google access:
cathy870208@gmail.com

## Group contacts info:
Please provide your expertise (1-3 keywords): Bioinformatics, Computational biology

## User info:
What is your [ORCID](https://orcid.org/register)?
[https://orcid.org/0000-0003-1287-0137](https://orcid.org/0000-0003-1287-0137)

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
National Tsing Hua University (NTHU)

Which group(s) are you a part of (if not the same as above)?

Which GOC member(s) directed you to this form? 

Will you be curating in Noctua?
Yes, my main purpose is to apply for a new Noctua account. I have also sent a letter to help@geneontology.org for applying for a new Noctua account. Thanks a lot!!
## Mailing list membership:
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
- [ ] Add user to Slack and appropriate rooms

**Comment by suzialeksander** [comment]
@c02080219, we haven't heard from you in a bit, if there's still anything you need let us know.
