### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by Mingsenli** [geneontology/helpdesk#377]
# Welcome to the Gene Ontology!

## Name: 
Mingsen Li

## Please *very* briefly describe your relation to the GO:
I am a researcher on ophthalmology.

## Please indicate your role:

I am a Biocurator

## GO Google access:

My email: lims3@mail2.sysu.edu.cn

## Group contacts info:
Please provide your expertise (1-3 keywords):

ophthalmology; epigenetics; stem cell biology

## User info:
What is your [ORCID](https://orcid.org/register)?
0000-0003-3019-3387

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 
State Key Laboratory of Ophthalmology, Zhongshan Ophthalmic Center, Sun Yat-sen University

Which group(s) are you a part of (if not the same as above)?

Which GOC member(s) directed you to this form? 
github

Will you be curating in Noctua?
 No

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
- [ ] Add user to Slack and appropriate rooms

**Comment by suzialeksander** [comment]
Hi @Mingsenli, are you just looking to browse the existing models? You can do that from http://geneontology.org/go-cam; if you're looking for GO data, you can find all releases at http://release.geneontology.org/

We only need this ticket for curators or programmers.  If you are part of a group involved with the Gene Ontology Consortium, and I have closed this ticket in error, please let me know & let me know what resources you need access to.  
Thanks!

**Comment by Mingsenli** [comment]
Dear GEO staff:
I want to submit a new GO terms. Do i performed a faulty operation?
please tell me the correct operation steps.
Thank you very much.


Sincerely yours,


Mingsen Li, PhD
Sun Yat-sen Ophthalmic Center, Sun Yat-sen University, China
***@***.***

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "suzialeksander"; 
Date: 2022年4月1日(星期五) 上午7:32
To: "geneontology/helpdesk"; 
Cc: "李名森"; "Mention"; 
Subject: Re: [geneontology/helpdesk] New User Onboarding (Issue #377)

&nbsp;


 
Hi @Mingsenli, are you just looking to browse the existing models? You can do that from http://geneontology.org/go-cam; if you're looking for GO data, you can find all releases at http://release.geneontology.org/
 
We only need this ticket for curators or programmers.  If you are part of a group involved with the Gene Ontology Consortium, and I have closed this ticket in error, please let me know &amp; let me know what resources you need access to.
 Thanks!
