### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#385]
# Welcome to the Gene Ontology!

## Name: 

Adding @manulera for Pombase as emailed from @ValWood 

## Please *very* briefly describe your relation to the GO:
This is so we know who you are and who to contact to get further information about groups, training status, etc.

## Please indicate your role:
You may indicate more than one ( [x] )

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can email our HelpDesk at "help" at our domain, geneontology.org, to avoid posting it publicly.

## Group contacts info:
Please provide your expertise (1-3 keywords):

## User info:
What is your [ORCID](https://orcid.org/register)?

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 

Which group(s) are you a part of (if not the same as above)?

Which GOC member(s) directed you to this form? 

Will you be curating in Noctua?

## Mailing list membership:
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
<s>- [ ] Add user to go-site/metadata/group-contacts.csv</s>
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups
- [x] Add user to Slack and appropriate rooms

**Comment by suzialeksander** [comment]
@ValWood I've added or sent invites for the above, as well as added the email provided to the GOC mailing list.  I'll be resending out a registration reminder for the meeting in the next week (probably Monday) through that list.  Is Manu planning on using Noctua? I have not yet added permissions for that, let me know if that's needed.

**Comment by manulera** [comment]
## Please briefly describe your relation to the GO

I am Biocurator at Pombase. As we curate papers we may request changes to the ontology.

## GO  Google access

I have sent an email requesting the access.

## Group contacts info

Cytoskeleton, Biophysics, Mitosis

## User info:

* ORCID: 0000-0002-8666-9746
* Organisation name: Pombase
* GOC member that directed me here: @ValWood 
* Curating in Noctua: Not that I know

## Mailing list

I have been added to the mailing list

**Comment by ValWood** [comment]
Yes please add @manulera Nocuta too. We will create a couple of models in Noctua  over the next few months so that we can check that Canto /go annotation  aligns fully  with Nocutua for creating causal models. We will export in the correct format to import in Noctua even though we do not plan to use for curation.

**Comment by kltm** [comment]
I've added @manulera to the go-consortium list, which should give them drive access.

**Comment by suzialeksander** [comment]
@ValWood, @manulera  should have Noctua permissions and be all set with everything else.
