### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by kimrutherford** [geneontology/helpdesk#389]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
Programmer at PomBase

## Please indicate your role:
You may indicate more than one ( [x] )

- [ ] Biocurator
- [ ] Domain expert
- [X] Software developer

## GO Google access:
kmr44@cam.ac.uk

## Group contacts info:
Please provide your expertise (1-3 keywords):
 - Programming
 - Bioinformatics

## User info:
What is your [ORCID](https://orcid.org/register)?
0000-0001-6277-726X

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?
PomBase

Which group(s) are you a part of (if not the same as above)?

Which GOC member(s) directed you to this form?
Kimberly Van Auken

Will you be curating in Noctua?
No, but I'd like to try it out

## Mailing list membership:
- [X] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups
- [x] Add user to Slack and appropriate rooms
