### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#392]
# Welcome to the Gene Ontology!

## Name: 
Colbie Reed
## Please *very* briefly describe your relation to the GO:
This is so we know who you are and who to contact to get further information about groups, training status, etc.

## Please indicate your role:
You may indicate more than one ( [x] )

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## GO Google access:
Please provide the email account you want to use for access to the GO Google Drive (shared documents) and GO Calendar (to view conference call information). You can email our HelpDesk at "help" at our domain, geneontology.org, to avoid posting it publicly.

(Colbie, I have your UFL address, please let me know if there is a different address you'd prefer)

## Group contacts info:
Please provide your expertise (1-3 keywords):

## User info:
What is your [ORCID](https://orcid.org/register)?

What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)? 

Which group(s) are you a part of (if not the same as above)?

Which GOC member(s) directed you to this form? 
@ValWood 
Will you be curating in Noctua?
Yes
## Mailing list membership:
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)

# Thank you for providing us with this information. 
When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO:
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups
- [x] Add user to Slack and appropriate rooms

**Comment by suzialeksander** [comment]
@ValWood  will Colbie be annotating on behalf of Pombase or is she the start of a whole new group joining to maintain these models in the future?

**Comment by ValWood** [comment]
Colbie will be annotating on behalf of PomBAse, but I think it would be useful to have an "assigned by " tag for the "De Crecy Lagard" group  so that anything Colbie or others contribute is attributed.
It might be possible to copy and edit the models for other species. They might also be interested in doing. microbial annotation since they have expertise in this area.

**Comment by dexink** [comment]
My GitHub handle is @dexink 
And my ORCID is 0000-0002-5039-2052

Thanks for having me aboard!

**Comment by dexink** [comment]
I've also subscribed to the GO consortium email list

**Comment by dexink** [comment]
@suzialeksander I thought I should tag you directly just in case you weren't notified of my preceding comments (above). From what I can see, this was all the information that I needed to forward/all actions possible for me to complete; is this accurate?

**Comment by suzialeksander** [comment]
@dexink sorry for the delay, adding a new group takes a bit longer to work out specifics but we're almost done.  Is there any web page for your lab/group? The most recent I can find is https://microcell.ufl.edu/valerie-de-crecy-lagard/ but that keeps 404ing.

**Comment by kltm** [comment]
Just a quick reminder that the URI for a group really should be immutable once it is in place. Since it is an identifier, not a URL, it's not strictly necessary to resolve to a web page or the like as long as we can continue to use it as a referential ID.

**Comment by dexink** [comment]
> @dexink sorry for the delay, adding a new group takes a bit longer to work out specifics but we're almost done. Is there any web page for your lab/group? The most recent I can find is https://microcell.ufl.edu/valerie-de-crecy-lagard/ but that keeps 404ing.

The live link should be: [https://microcell.ufl.edu/people/valerie-de-crecy-lagard/](https://microcell.ufl.edu/people/valerie-de-crecy-lagard/)

**Comment by dexink** [comment]
> I guess a project name is also needed for assigned by? If so @dexink do you want to confer with Valerie DeC about what this should be.
> 
> Usually the name is formed from the specific project, dataBase or institute so it could be something like UFL_OP ( for orphan proteins project) or something similar.
> 
> Examples from the "assigned by" column ARUK-UCL Alzheimers Research Gene Ontology Initiative ASAP A Systematic Annotation Package for Community Analysis of Genomes AgBase AgBase resource for functional analysis of agricultural plant and animal gene products Alzheimers_University_of_Toronto Alzheimers Project at BHF-UCL Cardiovascular Gene Ontology Annotation Initiative CACAO Community Assessment of Community Annotation with Ontologies
> 
> This "assigned by" tag will be used for any annotations you curate in Noctua, in addition to your personal ORCID.
> 
> The group could be added to "domain specific expertise" here: http://geneontology.org/docs/collaborations/as
> 
> Expertise in characterizing unknown enzymes, functional annotation accuracy, bioinformatics to identify and fill pathway holes (or similar).

Valerie supports your idea of "UF_OPP"

**Comment by suzialeksander** [comment]
Hi Colbie, you should have permissions now. Welcome!
