### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by pkalita-lbl** [geneontology/helpdesk#396]
# Welcome to the Gene Ontology!

## Name: 
Patrick Kalita

## Please *very* briefly describe your relation to the GO:
I recently joined [BBOP](https://berkeleybop.github.io/) as a developer and my work will occasionally have overlap with the GO.

## Indicate your role

- [ ] Biocurator
- [ ] Domain expert
- [x] Software developer

## Expertise for group contacts:

Web development

## User info
- What is your [ORCID](https://orcid.org/register)?:
0000-0002-6150-307X

- What is your preferred email for GO Google access?:
pkalita@lbl.gov

- What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?:
LBL

- Which group(s) are you a part of (if not the same as above)?:
BBOP

- Which GOC member(s) directed you to this form?:
@kltm 

- Will you be curating in Noctua?
- [ ] yes
- [x] no
- [ ] not sure

## Onboarding and Training

I have been directed to the GO Onboarding Checklists in the wiki
- [ ] yes
- [x] no

I have started training for Noctua, or have arranged with someone to start Noctua training
- [ ] yes
  - If yes, who is training you (person/event)?: 
- [ ] no
- [x] n/a, I'm not a curator and/or not using Noctua

## Mailing list membership
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)
________________
# Thank you for providing us with this information. 

What's next:
We will contact you if we have any questions, and we will close this ticket when have added all the needed permissions. 

When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
- [ ] Add user to Slack and appropriate rooms
- [ ] Direct user to wiki, including onboarding page

**Comment by kltm** [comment]
@suzialeksander This is a "new" developer at BBOP that we may be getting some time with for GO projects. I wanted to make sure that he has access to calendar, drive, etc. I believe we've already added him into the GH stuff.

**Comment by suzialeksander** [comment]
@kltm does he need a wiki account? that's not something we've been doing lately as standard but if there are any docs he'd need to update or anything on the wiki ... ?

**Comment by suzialeksander** [comment]
@pkalita-lbl since you already had some things set up, I think the rest have now been done.  There is an onboarding reference sheet at https://wiki.geneontology.org/New_member_onboarding that should have most of the links you need, etc.  If there's anything you can't access, just let me know.
