### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by Mingsenli** [geneontology/helpdesk#411]
# Welcome to the Gene Ontology!

## Indicate your role

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## User info
- What is your [ORCID](https://orcid.org/register)?: 0000-0003-3019-3387

- What is your preferred email for GO Google access?:  lims3@mail2.sysu.edu.cn
 

- What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?: Zhongshan Ophthalmic Center, Sun Yat-sen University

- Which group(s) are you a part of (if not the same as above)?: State Key Laboratory of Ophthalmology

- Which GOC member(s) directed you to this form?: Pascale

- Will you be curating in Noctua?
- [ ] yes
- [x] no
- [ ] not sure

## Onboarding and Training

I have been directed to the GO Onboarding Checklists in the wiki
- [ ] yes
- [x] no

I have started training for Noctua, or have arranged with someone to start Noctua training
- [ ] yes
  - If yes, who is training you (person/event)?: 
- [ ] no
- [x] n/a, I'm not a curator and/or not using Noctua

## Mailing list membership
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)
________________
# Thank you for providing us with this information. 

What's next:
We will contact you if we have any questions, and we will close this ticket when have added all the needed permissions. 

When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
- [ ] Add user to Slack and appropriate rooms
- [ ] Direct user to wiki, including onboarding page

**Comment by suzialeksander** [comment]
no action needed
