### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by lmoore207** [geneontology/helpdesk#422]
# Welcome to the Gene Ontology!

## Indicate your role

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## User info
- What is your [ORCID](https://orcid.org/register)?: 0000-0002-4114-1518

- What is your preferred email for GO Google access?: lisa.moore@sri.com
 

- What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?: SRI International

- Which group(s) are you a part of (if not the same as above)?: BioCyc/EcoCyc

- Which GOC member(s) directed you to this form?: Pascale Gaudet

- Will you be curating in Noctua?
- [ ] yes
- [x] no
- [ ] not sure

## Onboarding and Training

I have been directed to the GO Onboarding Checklists in the wiki
- [x] yes
- [ ] no

I have started training for Noctua, or have arranged with someone to start Noctua training
- [ ] yes
  - If yes, who is training you (person/event)?: 
- [ ] no
- [x] n/a, I'm not a curator and/or not using Noctua

## Mailing list membership
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)
________________
# Thank you for providing us with this information. 

What's next:
We will contact you if we have any questions, and we will close this ticket when have added all the needed permissions. 

When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO
- [ ] Add user to the GO Google Drive
- [ ] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [ ] Add user to GitHub and appropriate groups
- [ ] Add user to Slack and appropriate rooms
- [ ] Direct user to wiki, including onboarding page

**Comment by suzialeksander** [comment]
@lmoore207 thanks for this.  Google doesn't want to accept the sri email provided, do you have one that's connected to a Google account?

**Comment by lmoore207** [comment]
Hi Suzi,

I used to have my Macquarie Univ email account designated as the primary and just switched it to my new SRI Intl email. I can switch it back to the MQU account, which is linked to a Google account, as I still have an honorary position there. If that doesn’t work, then I could put it on my personal gmail, or make a new gmail for professional use (I probably should do that). What would you suggest?

Cheers, Lisa

From: suzialeksander ***@***.***>
Date: Friday, January 13, 2023 at 5:10 PM
To: geneontology/helpdesk ***@***.***>
Cc: Lisa Moore ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [geneontology/helpdesk] New User Onboarding (Issue #422)

@lmoore207<https://urldefense.us/v3/__https:/github.com/lmoore207__;!!Nv3xtKNH_4uope0!3qNakU9y2Yf2y-cDkz18NTVXUdGe29hxJJxNMR4Z_rXRY3A9dRXVTOXCQybjNg$> thanks for this. Google doesn't want to accept the sri email provided, do you have one that's connected to a Google account?

**Comment by suzialeksander** [comment]
Hi Lisa, it's up to you. If the honorary position is long-term, that should be fine, otherwise from personal experience I'd recommend a new work email so you can just turn it off on vacations/weekends.  Just let me know what you pick.

**Comment by suzialeksander** [comment]
Hey @lmoore207 did you have an email we can add so you can have access to the GO Shared Drive and our calls (through Google Calendar)? This doesn't have to be the one linked to this GitHub account, sorry if that part was unclear.

**Comment by lmoore207** [comment]
Hi Suzi,

Sorry I didn’t get back to you about this! Yes, we can use my MQU account as it will be good for another 2 yrs. It is ***@***.******@***.***>.

-Lisa

From: suzialeksander ***@***.***>
Date: Thursday, February 16, 2023 at 3:12 PM
To: geneontology/helpdesk ***@***.***>
Cc: Lisa Moore ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [geneontology/helpdesk] New User Onboarding (Issue #422)

Hey @lmoore207<https://urldefense.us/v3/__https:/github.com/lmoore207__;!!Nv3xtKNH_4uope0!3Qy7N6ea-iAn09usZdIXLwWTJRAFQBJKb-_IsRaVu49a4uLPYT8XYkKBIDifAg$> did you have an email we can add so you can have access to the GO Shared Drive and our calls (through Google Calendar)? This doesn't have to be the one linked to this GitHub account, sorry if that part was unclear.

**Comment by suzialeksander** [comment]
Done.  Note, no Noctua permissions at this point.
