### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by victorianugnes** [geneontology/helpdesk#436]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:

I am one of DisProt professional biocurator in charge of and reviewer of structural and function (GO) annotations abour intrinsically disordered regions (IDRs) in our database
## Indicate your role

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## Expertise for group contacts:

biocurator DisProt IDRs
## User info
- What is your [ORCID](https://orcid.org/register)?: 0000-0001-8399-7907

- What is your preferred email for GO Google access?: victorianugnesgmail.com
 

- What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?: DisProt

- Which group(s) are you a part of (if not the same as above)?: Biocomputing UP Lab

- Which GOC member(s) directed you to this form?: Pascale Gaudet

- Will you be curating in Noctua?
- [ ] yes
- [x] no
- [ ] not sure

## Onboarding and Training

I have been directed to the GO Onboarding Checklists in the wiki
- [x] yes
- [ ] no

I have an active account for the wiki
- [ ] yes
- [x] no

I have started training for Noctua, or have arranged with someone to start Noctua training
- [ ] yes
  - If yes, who is training you (person/event)?: 
- [ ] no
- [x] n/a, I'm not a curator and/or not using Noctua

## Mailing list membership
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)
________________
# Thank you for providing us with this information. 

What's next:
We will contact you if we have any questions, and we will close this ticket when have added all the needed permissions. 

When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/group-contacts.csv
- [ ] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups
- [x] Add user to Slack and appropriate rooms
- [ ] Direct user to wiki, including onboarding page
- [ ] Create wiki account

**Comment by suzialeksander** [comment]
Hi and welcome, @victorianugnes.  Most users don't need a GOwiki account, so if at any time you do need one just re-open this ticket or start a new ticket.  We've mostly shifted so many agendas, etc. are now G-docs instead of static wiki pages.  

Our meetings, including Tuesday annotation calls and the upcoming 2023 Spring GOC meeting, are linked from the Calendar and you should have access now -so if you have any issues let me know. 


Internal note: users.yaml not needed, groups.yaml already exists; user already directed to wiki onboarding; wiki account deferred until needed.
