### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by jmuysken** [geneontology/helpdesk#441]
# Welcome to the Gene Ontology!

## Please *very* briefly describe your relation to the GO:
I am a new curator with ZFIN

## Indicate your role
Curator

- [ x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## Expertise for group contacts:
Biocuration, zebrafish

## User info
- What is your [ORCID](https://orcid.org/register)?:0000-0002-7496-2937
- What is your preferred email for GO Google access?:jmuysken@uoregon.edu
 jmuysken@uoregon.edu

- What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?:ZFIN

- Which group(s) are you a part of (if not the same as above)?:

- Which GOC member(s) directed you to this form?:Kimberly Van Auken

- Will you be curating in Noctua?
- [ x] yes
- [ ] no
- [ ] not sure

## Onboarding and Training

I have been directed to the GO Onboarding Checklists in the wiki
- [ ] yes
- [ x] no

I have an active account for the wiki
- [ ] yes
- [ x] no

I have started training for Noctua, or have arranged with someone to start Noctua training
- [ x] yes
  - If yes, who is training you (person/event)?: Doug Howe
- [ ] no
- [ ] n/a, I'm not a curator and/or not using Noctua

## Mailing list membership
- [ ] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)
________________
# Thank you for providing us with this information. 

What's next:
We will contact you if we have any questions, and we will close this ticket when have added all the needed permissions. 

When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml
- [x] Add user to GitHub and appropriate groups
- [x] Add user to Slack and appropriate rooms
- [x] Direct user to wiki, including onboarding page
- [ ] ~~Create wiki account~~
- [ ] ~~Add user to go-site/metadata/group-contacts.csv~~

**Comment by suzialeksander** [comment]
Hey @jmuysken, welcome to GO!

The onboarding document can be found at https://wiki.geneontology.org/New_member_onboarding.  If you have any questions at all about the doc or onboarding, please let me know.  We do have a general website (geneontology.org), but most of our documentation for curators is on the wiki.  You should be able to access everything on the wiki without an account, and just to make your life simpler we aren't giving out wiki logins unless you need them (to edit).  If you at all think you need a wiki account, just let me know.

**Comment by suzialeksander** [comment]
Done, @jmuysken you should have all permissions needed for Noctua, annotation calls, and Drive access.  Let me know if you need anything else!
