### ISSUE TITLE
New User Onboarding

### ISSUE THREAD

**Issue by weichiatseng** [geneontology/helpdesk#460]
# Welcome to the Gene Ontology!

## Indicate your role

- [x] Biocurator
- [ ] Domain expert
- [ ] Software developer

## Expertise for group contacts:

Annotation
## User info
- What is your [ORCID](https://orcid.org/register)?:
Annotation
- What is your preferred email for GO Google access?:
 wtseng@uoregon.edu

- What is the name of your organization (e.g., LBL, SGD, EMBL-EBI)?:
ZFIN
- Which group(s) are you a part of (if not the same as above)?:

- Which GOC member(s) directed you to this form?:
Yvonne Bradford
- Will you be curating in Noctua?
- [x] yes
- [ ] no
- [ ] not sure

## Onboarding and Training

I have been directed to the GO Onboarding Checklists in the wiki
- [x] yes
- [ ] no

I have an active account for the wiki
- [ ] yes
- [x] no

I have started training for Noctua, or have arranged with someone to start Noctua training
- [x] yes
  - If yes, who is training you (person/event)?: Leyla Ruzicka
- [ ] no
- [ ] n/a, I'm not a curator and/or not using Noctua

## Mailing list membership
- [x] I've signed up for the GOC list (https://mailman.stanford.edu/mailman/listinfo/go-consortium)
________________
# Thank you for providing us with this information. 

What's next:
We will contact you if we have any questions, and we will close this ticket when have added all the needed permissions. 

When you are added as a member of the GO GitHub project, you automatically follow a number of repositories (different ones, depending on your role). By default, emails will be sent for all new and updated tickets. You can reduce this by going to the individual repo, and clicking on the 'eye' icon at the top right of the screen. We strongly recommend:

    Not watching: Be notified only when participating (ie when you comment on a ticket or manually watch it) or @mentioned. This is the optimal option to get relevant information. 

Please disregard the checklist below.  We will perform these internal tasks using the information provided above as soon as we can.

## To-Do by GO
- [x] Add user to the GO Google Drive
- [x] Add user to the GO Google Calendar
- [ ] Add user to go-site/metadata/group-contacts.csv
- [x] Add user to go-site/metadata/users.yaml and any additional groups to go-site/metadata/groups.yaml; refresh Noctua users if needed
- [x] Add user to GitHub and appropriate groups
- [x] Add user to Slack and appropriate rooms
- [ ] Direct user to wiki, including onboarding page
- [ ] Create wiki account
